### ISSUE TITLE
It doesn't works anymore.

### ISSUE THREAD

**Issue by CyberByte-js** [BayGamerYT/Fortnite-Discord-RPC#1]
When I try to run main.py it gives a giant error:
![image](https://user-images.githubusercontent.com/71409005/107156562-dae13780-695d-11eb-9071-6aa68c6b36cd.png)
I use it everyday and only today it is giving this error.

**Comment by Not-Bay** [comment]
Recently epic games removed the device auths from bots accounts (credentials needed to login) This doesn't happen very often, download the repository and do the setup again.

**Comment by CyberByte-js** [comment]
If "download the repository" means re-download, I did it and the same thing happened.

**Comment by Not-Bay** [comment]
You need to do the setup again to generate new credentials (when you are prompted for an authorization code).

**Comment by CyberByte-js** [comment]
Oh, ok thanks

**Comment by CyberByte-js** [comment]
Wait, actually, that was what I did when i reinstalled it.

**Comment by Not-Bay** [comment]
It works for me without any problems, I just did the verification and I can use it normally. I can't tell you what's going on
